FROM node:20-alpine AS builder

WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY . .
RUN npm run build


FROM node:20-alpine AS runner

WORKDIR /app

ENV NODE_ENV=production
ENV VITE_API_BASE_URL=http://localhost:5000

RUN npm install -g serve --omit=dev && npm cache clean --force

COPY --from=builder /app/dist ./dist

EXPOSE 3000

CMD sh -c "echo \"window.__ENV__ = { VITE_API_BASE_URL: '$VITE_API_BASE_URL' };\" > ./dist/env.js && serve -s dist -l 3000"