FROM node:20-alpine AS runner

WORKDIR /app

RUN npm install -g serve

# runtime env support
ENV VITE_API_BASE_URL=http://localhost:5000

COPY --from=builder /app/dist ./dist

# inject runtime env into static files
RUN echo "window.__ENV__ = { VITE_API_BASE_URL: '$VITE_API_BASE_URL' };" > ./dist/env.js

EXPOSE 3000

CMD sh -c "echo \"window.__ENV__ = { VITE_API_BASE_URL: '$VITE_API_BASE_URL' };\" > ./dist/env.js && serve -s dist -l 3000"