
services:
  backend:
    build:
      context: ./backend
    container_name: backend
    restart: always
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_BASE_URL: ${VITE_API_BASE_URL}
    container_name: frontend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge